[mgr]
sort_dir_first = true
show_hidden = true

[preview]
wrap = "yes"
image_filter = "triangle"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
